name: "Semantic version"
inputs:
  token:
    required: true
    default: "$GITHUB_TOKEN"

outputs:
  current-version:
    value: ${{ steps.current.outputs.version }}
  next-version:
    value: ${{ steps.next.outputs.version }}

runs:
  using: "composite"
  steps:
    - id: current
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        VERSION=$(git tag -l --sort=-creatordate | head -n 1 | tr -d v)
        echo "::set-output name=version::$(echo $VERSION)"
      shell: bash

    - id: next
      run: |
        npx semantic-release --dry-run --branches=$(git branch --show)
        VERSION=$(test -e .VERSION && cat .VERSION)
        echo "::set-output name=version::$(echo $VERSION)"
      shell: bash
      env:
        GITHUB_TOKEN: ${{inputs.token}}
