name: "Semantic version"
inputs:
  init-version:
    default: "1.0.0"
  token:
    required: true
    default: "$GITHUB_TOKEN"
  path:
    required: true
    default: "$SEMANTIC_PATH"

outputs:
  current-version:
    value: ${{ steps.current.outputs.version }}
  next-version:
    value: ${{ steps.next.outputs.version }}

runs:
  using: "composite"
  steps:
    - id: current
      name: Determine current version from git tags
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        VERSION=$(git tag -l --sort=-creatordate | head -n 1 | tr -d v)
        echo "::set-output name=version::$(echo $VERSION)"
      shell: bash

    - name: Create folder with alternative config file
      run: |
        cp -rv ${{ inputs.path }}/semantic-version/.release-bot ./
      shell: bash

    - name: Run semantic release
      run: |
        cd ./.release-bot
        npx semantic-release --dry-run --branches=$(git branch --show)
        ls -al
      shell: bash
      env:
        GITHUB_TOKEN: ${{inputs.token}}

    - id: next
      name: Calculate next version with semantic-release
      run: |
        SEMVER=$(test -e .VERSION && cat .VERSION)
        VERSION=$(test "${{ steps.current.outputs.version }}" && echo "$SEMVER" || echo "${{ inputs.init-version }}")
        test "$VERSION" && echo "::set-output name=version::$(echo $VERSION)"
      shell: bash
