name: "Semantic version"
inputs:
  init-version:
    default: "1.0.0"
  token:
    required: true
    default: "$GITHUB_TOKEN"
  path:
    required: true
    default: "$SEMANTIC_PATH"

outputs:
  current-version:
    value: ${{ steps.current.outputs.version }}
  next-version:
    value: ${{ steps.next.outputs.version }}

runs:
  using: "composite"
  steps:
    - id: current
      run: |
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        VERSION=$(git tag -l --sort=-creatordate | head -n 1 | tr -d v)
        echo "::set-output name=version::$(echo $VERSION)"
      shell: bash

    - run: |
        cp -rv ${{ inputs.path }}/semantic-version/.release-bot ./
        cd ./.release-bot
        ls -al
      shell: bash

    - id: next
      run: |
        npx semantic-release --dry-run --branches=$(git branch --show)
        SEMVER=$(test -e .VERSION && cat .VERSION)
        VERSION=$(test ${{ steps.current.outputs.version }} && echo "$SEMVER" || echo "${{ inputs.init-version }}")
        echo "::set-output name=version::$(echo $VERSION)"
      shell: bash
      env:
        GITHUB_TOKEN: ${{inputs.token}}
