name: "Setup Java"
inputs:
  distribution:
    default: 'temurin'
  java-version:
    default: '16'
  username:
    default: "GITHUB"
  token:
    required: true

runs:
  using: "composite"
  steps:
    - run: echo "$MYVAR"
      shell: bash

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: ${{ inputs.distribution  }}
        java-version: ${{ inputs.java-version  }}

    - uses: s4u/maven-settings-action@v2.4.1
      with:
        servers: |
          [{"id": "github-kepler",
            "username": "${{ inputs.username }}",
            "password": "${{ inputs.token }}"},
           {"id": "github-transit",
            "username": "${{ inputs.username }}",
            "password": "${{ inputs.token }}"}]
