name: "Setup Java"
inputs:
  distribution:
    default: 'temurin'
  java-version:
    default: '16'
  username:
    default: 'GITHUB'
  token:
    default: "$GITHUB_TOKEN"

runs:
  using: "composite"
  steps:
    - run: |
        echo "inputs ${{ inputs.token }}"
        echo "env $GITHUB_TOKEN"
      shell: bash

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: ${{ inputs.distribution  }}
        java-version: ${{ inputs.java-version  }}

    - uses: s4u/maven-settings-action@v2.4.1
      with:
        servers: |
          [{"id": "github-kepler",
            "username": "${{ inputs.username }}",
            "password": "${{ $GITHUB_TOKEN }}"},
           {"id": "github-transit",
            "username": "${{ inputs.username }}",
            "password": "${{ $GITHUB_TOKEN }}"}]
