name: "Setup Java"
inputs:
  distribution:
    default: 'temurin'
  java-version:
    default: '16'
  username:
    default: 'GITHUB'
  token:
    description: "GITHUB_TOKEN"

runs:
  using: 'composite'

  steps:
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: ${{ inputs.distribution  }}
        java-version: ${{ inputs.java-version  }}

    - uses: s4u/maven-settings-action@v2.4.1
      env:
        PASSWORD: ${{ inputs.token }} || ${{ env.GITHUB_TOKEN }}
      with:
        servers: |
          [{"id": "github-kepler",
            "username": "${{ inputs.username }}",
            "password": "$PASSWORD"},
           {"id": "github-transit",
            "username": "${{ inputs.username }}",
            "password": "$PASSWORD"}]
