name: "Setup Java"
inputs:
  distribution:
    default: 'temurin'
  java-version:
    default: '16'

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: ${{ inputs.distribution  }}
        java-version: ${{ inputs.java-version  }}

    - uses: s4u/maven-settings-action@v2.4.1
      with:
        servers: |
          [{"id": "github-kepler",
            "username": "GITHUB",
            "password": "${{secrets.GITHUB_TOKEN}}"},
           {"id": "github-transit",
            "username": "GITHUB"
            "password": "${{secrets.GITHUB_TOKEN}}"}]
