name: "Setup Clojure"

runs:
  using: "composite"
  steps:
    - uses: DeLaGuardo/setup-clojure@3.7
      with:
        cli: latest

    - name: Setup Babashka
      run: |
        bash < <(curl -s https://raw.githubusercontent.com/babashka/babashka/master/install)

