name: "Setup Clojure"
inputs:
  paths:
    default: '**/deps.edn'
  clojure-version:
    default: "latest"
  use-cache:
    default: 'yes'
  key:
    default: cljdeps-${{ hashFiles('**/deps.edn') }}
  restore-keys:
    default: cljdeps-
  path:
    default: |
      ~/.m2/repository
      ~/.gitlibs
      ~/.deps.clj

runs:
  using: "composite"
  steps:

    - name: Install Clojure Tools
      uses: DeLaGuardo/setup-clojure@10.2
      with:
        cli: ${{ inputs.clojure-version }}
        bb: latest

    - name: Cache Clojure Dependencies
      if: inputs.use-cache == 'yes'
      uses: actions/cache@v3
      with:
        path: ${{ inputs.path }}
        keys: ${{ inputs.key }}
        restore-keys: ${{ inputs.restore-keys }}
