name: "Setup Node"
inputs:
  node-version:
    default: "18"
  cache:
    default: "npm"
  use-cache:
    default: "yes"
  package:
    default: "npm"
  always-auth:
    default: true
  registry-url:
    description: "npm registry url"
    default: "https://npm.pkg.github.com"
  scope:
    description: "npm scope if any"
    default: "@transit-engineering"

runs:
  using: "composite"
  steps:
    - name: Setup pnpm
      if: inputs.package == 'pnpm'
      uses: pnpm/action-setup@v2.0.1
      with:
        version: latest

    - name: Setup Node
      if: inputs.use-cache != 'yes'
      uses: actions/setup-node@v3
      with:
        always-auth: ${{ inputs.always-auth }}
        registry-url: ${{ inputs.registry-url }}
        scope: ${{ inputs.scope }}
        node-version: ${{ inputs.node-version }}

    - name: Setup Node
      if: inputs.use-cache == 'yes'
      uses: actions/setup-node@v3
      with:
        always-auth: ${{ inputs.always-auth }}
        registry-url: ${{ inputs.registry-url }}
        scope: ${{ inputs.scope }}
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.package }}

    - name: Cache npm dependencies
      if: inputs.use-cache == 'yes' && inputs.package == 'npm' && inputs.cache == 'npm'
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
