name: "Setup Node"
inputs:
  node-version:
    default: "16"
  cache:
    default: "npm"
  use-cache:
    default: "yes"
  package:
    default: "npm"

runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}

    - name: Cache npm dependencies
      if: ${{ inputs.use-cache == 'yes' && inputs.package == 'npm' }}
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
