name: "Setup Gooogle Cloud SDK"
inputs:
  credentials_json:
    description: service account key
  project_id:
    default: "transit-root"
  show_info:
    default: "no"

runs:
  using: "composite"
  steps:
    - name: Gcloud Authentication
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ inputs.credentials_json }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ inputs.project_id }}

    - name: Use gcloud CLI
      if: inputs.show_info != 'yes'
      shell: bash
      run: gcloud info
